### ISSUE TITLE
Roadmap to v1.0

### ISSUE THREAD

**Issue by oovm** [paclets/PackPaclet.js#1]
## Features

- [ ] Packing on a CI server and uploading to github or other places

- [ ] Distinguish between minimal installation packages and complete installation packages with documentation and resources

- [ ] Automatically update the minor version number

---

## Options

- **Root**: Folder that needs to be packaged
- **FilterPath**: A json contains following keys:
  - Exclude: Patterns to remove files. (Path inherits **Root**)
  - Include: Patterns to include some of the removed files
  - Documentation: The documentation folder path which will not be included in min package
- **GithubKey**: Used to upload to github release
- **AutoVersion**: If enabled, the minor version number set in `PacletInfo.m` will be ignored, and the last digit of each release will be +1.
- **PreRelease**: If enabled, all the release version will use the pre-release tag
